# mihomo文档 h(tps://wiki.metacubex.one/config/dns/hosts/#hosts

mode: rule # 规则模式
mixed-port: 7890 # socks/http代理端口
redir-port: 7892 # redirect透明代理端口
tproxy-port: 7893 # tproxy透明代理端口
allow-lan: true # 允许局域网访问
ipv6: true # 开启ipv6
unified-delay: true #统一延迟
log-level: info # 日志等级

tcp-concurrent: true # 启用 TCP 并发连接

# TCP Keep Alive 设置，减少设备耗电问题
keep-alive-interval: 30
keep-alive-idle: 15

find-process-mode: strict # 进程查找模式
global-client-fingerprint: chrome # 全局客户端指纹模拟为 Chrome 浏览器

# 自动更新geo
geox-url:
  geosite: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  mmdb: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
  geoip: https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat
  asn: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 6

# 域名嗅探 https://wiki.metacubex.one/config/sniff/#_1
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
    - "+.push.apple.com"

# 缓存
profile:
  store-selected: true
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

# 自动同步时间以防止时间不准导致无法正常联网
ntp:
  enable: true
  # 是否同步至系统时间，需要 root/管理员权限
  write-to-system: false
  server: time.apple.com
  port: 123
  interval: 30

# 管理页面 https://wiki.metacubex.one/config/general/#_7
external-controller: 127.0.0.1:9090
# external-ui: yacd
external-ui: zashboard #使用zashboard为本地管理ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"
bind-address: "*"

# tun虚拟网卡设置 不懂默认就好 默认开启tun
tun:
  enable: true
  device: mihoyo
  stack: mixed
  auto-route: true # 自动添加路由
  strict-route: true # 严格路由模式
  endpoint-independent-nat: true # 启用端点独立 NAT
  auto-redirect: true # 自动重定向流量到 TUN 设备
  auto-detect-interface: true # 自动检测网络接口
  dns-hijack: 
    - any:53


# https://wiki.metacubex.one/config/dns/hosts/#hosts
hosts:
  doh.pub: [1.12.12.21, 120.53.53.53, 1.12.12.12]
  dot.pub: [1.12.12.21, 120.53.53.53, 1.12.12.12]
  "*.alidns.com": [223.5.5.5, 223.6.6.6, 2400:3200::1, 2400:3200:baba::1]
  dns.google: [8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001]
  "*.cloudflare-gateway.com": [162.159.36.20, 162.159.36.5, 2606:4700:5c::a29f:2e07, 2606:4700:54::a29f:2407]

dns:
  enable: true
  listen: 0.0.0.0:1053
  cache-algorithm: arc # DNS 缓存算法
  ipv6: false # 启用 IPv6 解析
  respect-rules: true # 遵循分流规则
  enhanced-mode: redir-host
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - https://1.12.12.21/dns-query
    - https://223.5.5.5/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://xxxxxxxxxx.cloudflare-gateway.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://dot.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:geolocation-!cn,gfw,!cn":
      - https://dns.google/dns-query
      - https://xxxxxxxxxx.cloudflare-gateway.com/dns-query


proxies:
# mihomo配置参考可以看看这个wiki
# https://wiki.metacubex.one

#预设
pr: &pr
  type: select
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    timeout: 3000
  include-all: true


autotest: &autotest
  type: url-test
  interval: 300
  tolerance: 100
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 120
    timeout: 3000
  include-all: true


p: &p
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    timeout: 1500
    interval: 300
    lazy: true

# 代理提供(订阅)组
# url 里填写自己的订阅,名称不能重复
proxy-providers:
  Aries: 
    <<: *p
    url: "https://gist.githubusercontent.com/yuanwangokk-1/51ae278f2a2d697a9f32e983f3275b7c/raw/ec88b831c107fb8112b9b8100261f3906de6dd38/config.json"
    # path: ./proxy_providers/jichang1.yaml #指定保存路径 非必填

  # 机场2: #机场名
    # <<: *p
    # url: "这里填机场订阅"
    # path: ./proxy_providers/jichang2.yaml #保存路径

# 代理组
proxy-groups:
  - name: 代理设置
    type: select
    proxies:
      - 国内分流
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 全部节点

  - name: 国内分流
    type: select
    proxies:
      - DIRECT
      - 中国

  - name: 屏蔽
    type: select
    proxies:
      - REJECT-DROP
      - REJECT
      - DIRECT

  - name: AI分流
    type: select
    proxies:
      - 代理设置
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 英国
      - 美国
      - 全部节点


# 按照区域划定策略组
  - {name: 中国, <<: *pr, proxies: [中国自动选择], filter: "(?i)(🇨🇳|中国|cn|china|CN)", exclude-filter: "(?i)(台湾|tw|taiwan|TW)"}
  - {name: 香港, <<: *pr, proxies: [香港自动选择], filter: "(?i)(🇭🇰|香港|hk|hongkong|hong kong|HK)"}
  - {name: 台湾, <<: *pr, proxies: [台湾自动选择], filter: "(?i)(台湾|tw|taiwan|TW)"}
  - {name: 日本, <<: *pr, proxies: [日本自动选择], filter: "(?i)(🇯🇵|日|jp|japan|JP)"}
  - {name: 美国, <<: *pr, proxies: [美国自动选择], filter: "(?i)(🇺🇸|美|us|unitedstates|united states|US)"}
  - {name: 英国, <<: *pr, proxies: [英国自动选择], filter: "(?i)(🇬🇧|英国|uk|英国|England|UK)"}
  - {name: 新加坡, <<: *pr, proxies: [新加坡自动选择], filter: "(?i)(🇸🇬|新加坡|sg|singapore|SG)"}
  - {name: 全部节点, proxies: [自动选择], <<: *pr}
  # 下面这段为自动选择不会在面板显示 如果显示了说明你的面板不支持hidden字段
  - {name: 中国自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇨🇳|中国|cn|china|CN)", exclude-filter: "(?i)(台湾|tw|taiwan|TW)"}
  - {name: 香港自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇭🇰|香港|hk|hongkong|hong kong|HK)"}
  - {name: 台湾自动选择, <<: *autotest, hidden: true, filter: "(?i)(台湾|tw|taiwan|TW)"}
  - {name: 日本自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇯🇵|日|jp|japan|JP)"}
  - {name: 美国自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇺🇸|美|us|unitedstates|united states|US)"}
  - {name: 英国自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇬🇧|英国|uk|英国|England|UK)"}
  - {name: 新加坡自动选择, <<: *autotest, hidden: true, filter: "(?i)(🇸🇬|新加坡|sg|singapore|SG)"}
  - {name: 自动选择, <<: *autotest, hidden: true}

# 分流规则提供(订阅)组
rule-providers:
  AWAvenue:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/AWAvenue-Ads-Rule-Clash.yaml
    url: "https://gcore.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"
    interval: 60480

# 分流规则
rules:

  - AND,((NOT,((OR,((PROCESS-NAME,mihomo),(PROCESS-NAME,ClashMeta))))),(DST-PORT,853)),屏蔽 #禁止非mihomo访问dot dns
  - GEOSITE,category-httpdns-cn,屏蔽 #屏蔽httpdns防止去广告失效
  - RULE-SET,AWAvenue,屏蔽 #去广告
  - IP-CIDR,203.107.1.0/24,屏蔽,no-resolve # 阿里云ip httpdns

  - GEOSITE,private,国内分流
  - GEOSITE,connectivity-check,国内分流
  - GEOSITE,googlefcm,国内分流
  - GEOSITE,category-games@cn,国内分流
  - GEOSITE,cn,国内分流
  - GEOIP,PRIVATE,国内分流,no-resolve
  - GEOIP,cn,国内分流,no-resolve
  - GEOSITE,category-ai-!cn,AI分流
  - GEOSITE,geolocation-!cn,代理设置
  - MATCH,代理设置

